apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-fiks-service
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
  accessPolicy:
    outbound:
      external:
        - host: api.fiks.ks.no
        - host: minside.kommune.no
      rules:
        - application: norg2
          namespace: org
    inbound:
      rules:
        - application: sosialhjelp-innsyn
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  valkey:
    - instance: cache
      access: readwrite
  envFrom:
    - secret: fiks-integrasjon-secret
  env:
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "https://api.fiks.ks.no"
    - name: FIKS_DOKUMENTLAGER_ENDPOINT_URL
      value: "https://minside.kommune.no"
    - name: NORG_ENDPOINT_URL
      value: "http://norg2.org/norg2/api/v1"
