apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-fiks-service
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "82efbcf9-7a99-4c60-9242-79c439ca3cdc" # 0000-GA-Modia_Sosialhjelp_NKS
          - id: "beca52a8-5551-4db0-9860-78355b796f14" # team digisos
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
  accessPolicy:
    outbound:
      external:
        - host: api.fiks.ks.no
        - host: minside.kommune.no
        - host: pdl-api.prod-fss-pub.nais.io
      rules:
        - application: norg2
          namespace: org
        - application: skjermede-personer-pip
          namespace: nom
    inbound:
      rules:
        - application: sosialhjelp-innsyn-api
        - application: sosialhjelp-modia-api
        - application: sosialhjelp-adminpanel
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  valkey:
    - instance: cache
      access: readwrite
  envFrom:
    - secret: fiks-integrasjon-secret
    - secret: fiks-service-secrets
  env:
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "https://api.fiks.ks.no"
    - name: NORG_ENDPOINT_URL
      value: "http://norg2.org/norg2/api/v1"
    - name: PDL_ENDPOINT_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SKJERMEDE_PERSONER_ENDPOINT_URL
      value: "http://skjermede-personer-pip.nom"
