name: 'Build Kotlin, Run Lint and Test'
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: 'Build with Gradle'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - name: Build kotlin, and run tests
        uses: navikt/sosialhjelp-ci/actions/build-kotlin@v21
        with:
          java-version: '21'
          lint: 'false'
